name: qbert
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cytoolz=0.9.0.1=py37h14c3975_1
  - decorator=4.4.0=py37_1
  - dill=0.2.9=py37_0
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.5.6=py37h6bb024c_1
  - murmurhash=0.28.0=py37hf484d3e_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - nltk=3.4.5=py37_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.2.2=py37_0
  - plac=0.9.6=py37_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.0=py37_0
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - regex=2018.07.11=py37h14c3975_0
  - requests=2.22.0=py37_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tqdm=4.32.1=py_0
  - ujson=1.35=py37h14c3975_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - cuda90=1.0=h6433d27_0
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - atari-py==0.2.6
    - blis==0.4.1
    - boto3==1.12.49
    - botocore==1.15.49
    - cachetools==4.0.0
    - catalogue==1.0.0
    - click==7.0
    - cloudpickle==1.2.2
    - cycler==0.10.0
    - cymem==2.0.3
    - docutils==0.15.2
    - filelock==3.0.12
    - flask==1.1.1
    - future==0.17.1
    - fuzzywuzzy==0.17.0
    - gast==0.2.2
    - gevent==1.3.5
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - greenlet==0.4.13
    - grpcio==1.26.0
    - gym==0.10.4
    - h5py==2.10.0
    - hashids==1.2.0
    - importlib-metadata==1.5.0
    - itsdangerous==1.1.0
    - jericho==2.4.2
    - jinja2==2.10.1
    - jmespath==0.9.5
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - loky==2.6.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - msgpack==0.5.6
    - oauthlib==3.1.0
    - opencv-python==4.1.1.26
    - opt-einsum==3.1.0
    - pillow==6.1.0
    - preshed==3.0.2
    - prompt-toolkit==2.0.9
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybars3==0.9.6
    - pydot==1.4.1
    - pyglet==1.4.4
    - pymeta3==0.5.1
    - pyopengl==3.1.0
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - python-levenshtein==0.12.0
    - pyyaml==5.1.2
    - redis==3.3.8
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.41
    - scipy==1.4.1
    - selenium==3.141.0
    - sentencepiece==0.1.83
    - spacy==2.2.3
    - srsly==1.0.1
    - tatsu==4.4.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - thinc==7.3.1
    - tokenizers==0.5.2
    - torch==1.4.0
    - transformers==2.8.0
    - wasabi==0.6.0
    - wcwidth==0.1.7
    - werkzeug==0.15.6
    - wrapt==1.11.2
    - zipp==2.1.0
